# Generated by Django 3.1.6 on 2021-02-20 02:25

import classify.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=4)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('is_doctor', models.BooleanField(default=False)),
                ('phoneno', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=100)),
                ('tier', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lungs_status', models.CharField(max_length=30)),
                ('remarks', models.CharField(max_length=200)),
                ('test_date', models.DateTimeField(default=datetime.datetime.now)),
                ('x_ray', models.ImageField(upload_to=classify.models.Record.user_directory_path)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.person')),
            ],
        ),
    ]
