# Generated by Django 3.1.6 on 2021-02-21 07:44

import classify.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0002_auto_20210220_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='test_date',
            field=models.DateTimeField(default=classify.models.Record.time_date),
        ),
    ]
